### ISSUE TITLE
Feature Request: Ability to pass current buffer to preset commands

### ISSUE THREAD

**Issue by TonySherman** [google/executor.nvim#19]
This might be possible already and my lua knowledge is just lacking 😄 

I would like to be able to pass the current buffer's file path as an argument to a preset command.

I attempted the following:

```lua
local executor = require('executor')

local current_buffer = vim.api.nvim_get_current_buf()
local file_path = vim.api.nvim_buf_get_name(current_buffer)

executor.setup({
	preset_commands = {
		["preset_dir"] = {
			{ "make test  test_path=" .. file_path },
		},
	}
})
```

I don't believe I am getting the file path correctly either as this would be the complete path on my system and I would want it relative to the project I am in. Regardless, it sees the root directory of the project as the `file_path` rather than the current buffer's path.

**Comment by jackfranklin** [comment]
Ah no this won't currently work as all that code is evaluated when Vim loads.

I think the API here would have to be something like:

```lua
["preset_dir"] = {
  function(bufnr) "make test test_path=" .. file_path_for_buf(bufnr) end
}
```

**Comment by TonySherman** [comment]
I did a little digging and tried change [this](https://github.com/google/executor.nvim/blob/main/lua/executor/init.lua#L60) to using the `nvim_buf_create_user_command` but that didn't register the command and I know very little about Neovim plugin development in general.

If I knew a little more about how to implement this, I would get a PR together but that unfortunately isn't likely to happen very quickly.

**Comment by jackfranklin** [comment]
@TonySherman does the PR above solve your case here? It does not pass in the current bufnr, but that is because in Neovim's API the buffer ID `0` always means "current buffer ID"

**Comment by TonySherman** [comment]
The example does give the full file path, not the path relative to the project directory that you're in. That's still fixable on my end and just allowing a function to be passed in solves this issue.

**Comment by TonySherman** [comment]
In my case, I had to change `local buf_name = vim.api.nvim_buf_get_name(0)` to `local buf_name = vim.fn.expand('%')` but I don't know if my use case is specific enough to change your doc updates for.
