### ISSUE TITLE
Popup is not showing when I try to run an command

### ISSUE THREAD

**Issue by Auha** [google/executor.nvim#27]
## Expected Behavior

In my config, I have `use_split = false` but when I run the command `:ExecutorRun` the first time I am expecting the prompt to be a popup.

## Actual Behavior

Instead of a popup it is just  the command line prompt at the bottom. 

Am I missing something? 

Version: Latest
OS: MacOS.

**Comment by jackfranklin** [comment]
I think this is the expected behaviour, the command that you run will always be inputted via a prompt at the bottom.

The use_split / use_popup behaviour is for viewing the results after a command has run.

**Comment by Auha** [comment]
The only reason I made this issue was due to the some of the short movies in the documentation where the commands are entered in via a popup.
